//
// AutoUploadCalibarationFactor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class AutoUploadCalibarationFactor: Codable {

    public var value: Double?


    
    public init(value: Double?) {
        self.value = value
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(value, forKey: "value")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        value = try container.decodeIfPresent(Double.self, forKey: "value")
    }
}

