//
// ChangePasswordWithTempPasswordViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Change Password */

public class ChangePasswordWithTempPasswordViewModel: Codable {

    /** Gets or sets the email. */
    public var email: String
    /** Gets or sets the temporary password. */
    public var tempPassword: String?
    /** Gets or sets the new password. */
    public var newPassword: String


    
    public init(email: String, tempPassword: String?, newPassword: String) {
        self.email = email
        self.tempPassword = tempPassword
        self.newPassword = newPassword
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(email, forKey: "email")
        try container.encodeIfPresent(tempPassword, forKey: "tempPassword")
        try container.encode(newPassword, forKey: "newPassword")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        email = try container.decode(String.self, forKey: "email")
        tempPassword = try container.decodeIfPresent(String.self, forKey: "tempPassword")
        newPassword = try container.decode(String.self, forKey: "newPassword")
    }
}

