//
// Companyinformation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class Companyinformation: Codable {

    public var address: AddressFromDevice?
    public var licenseNumber: String?


    
    public init(address: AddressFromDevice?, licenseNumber: String?) {
        self.address = address
        self.licenseNumber = licenseNumber
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(address, forKey: "address")
        try container.encodeIfPresent(licenseNumber, forKey: "licenseNumber")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        address = try container.decodeIfPresent(AddressFromDevice.self, forKey: "address")
        licenseNumber = try container.decodeIfPresent(String.self, forKey: "licenseNumber")
    }
}

