//
// CreateInspectionViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class CreateInspectionViewModel: Codable {

    public var testNumber: String?
    public var deviceId: Int64?


    
    public init(testNumber: String?, deviceId: Int64?) {
        self.testNumber = testNumber
        self.deviceId = deviceId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(testNumber, forKey: "testNumber")
        try container.encodeIfPresent(deviceId, forKey: "deviceId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        testNumber = try container.decodeIfPresent(String.self, forKey: "testNumber")
        deviceId = try container.decodeIfPresent(Int64.self, forKey: "deviceId")
    }
}

