//
// CRMAccount.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class CRMAccount: Codable {

    public var id: String?
    public var name: String?
    public var billingAddress: CRMAddress?
    public var createdDate: String?
    public var systemModstamp: String?


    
    public init(id: String?, name: String?, billingAddress: CRMAddress?, createdDate: String?, systemModstamp: String?) {
        self.id = id
        self.name = name
        self.billingAddress = billingAddress
        self.createdDate = createdDate
        self.systemModstamp = systemModstamp
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(billingAddress, forKey: "billingAddress")
        try container.encodeIfPresent(createdDate, forKey: "createdDate")
        try container.encodeIfPresent(systemModstamp, forKey: "systemModstamp")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(String.self, forKey: "id")
        name = try container.decodeIfPresent(String.self, forKey: "name")
        billingAddress = try container.decodeIfPresent(CRMAddress.self, forKey: "billingAddress")
        createdDate = try container.decodeIfPresent(String.self, forKey: "createdDate")
        systemModstamp = try container.decodeIfPresent(String.self, forKey: "systemModstamp")
    }
}

