//
// Customerinformation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class Customerinformation: Codable {

    public var billingAddress: Billingaddress?
    public var siteAddress: Siteaddress?


    
    public init(billingAddress: Billingaddress?, siteAddress: Siteaddress?) {
        self.billingAddress = billingAddress
        self.siteAddress = siteAddress
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(billingAddress, forKey: "billingAddress")
        try container.encodeIfPresent(siteAddress, forKey: "siteAddress")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        billingAddress = try container.decodeIfPresent(Billingaddress.self, forKey: "billingAddress")
        siteAddress = try container.decodeIfPresent(Siteaddress.self, forKey: "siteAddress")
    }
}

