//
// DataTableUnitModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class DataTableUnitModel: Codable {

    public var radon: String?
    public var tempC: String?
    public var pres: String?
    public var humidity: String?


    
    public init(radon: String?, tempC: String?, pres: String?, humidity: String?) {
        self.radon = radon
        self.tempC = tempC
        self.pres = pres
        self.humidity = humidity
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(radon, forKey: "radon")
        try container.encodeIfPresent(tempC, forKey: "tempC")
        try container.encodeIfPresent(pres, forKey: "pres")
        try container.encodeIfPresent(humidity, forKey: "humidity")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        radon = try container.decodeIfPresent(String.self, forKey: "radon")
        tempC = try container.decodeIfPresent(String.self, forKey: "tempC")
        pres = try container.decodeIfPresent(String.self, forKey: "pres")
        humidity = try container.decodeIfPresent(String.self, forKey: "humidity")
    }
}

