//
// DeleteHomeDeviceModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class DeleteHomeDeviceModel: Codable {

    public var deviceId: Int64?
    public var userId: Int64?
    public var latitude: Double?
    public var longtitude: Double?


    
    public init(deviceId: Int64?, userId: Int64?, latitude: Double?, longtitude: Double?) {
        self.deviceId = deviceId
        self.userId = userId
        self.latitude = latitude
        self.longtitude = longtitude
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(deviceId, forKey: "deviceId")
        try container.encodeIfPresent(userId, forKey: "userId")
        try container.encodeIfPresent(latitude, forKey: "latitude")
        try container.encodeIfPresent(longtitude, forKey: "longtitude")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        deviceId = try container.decodeIfPresent(Int64.self, forKey: "deviceId")
        userId = try container.decodeIfPresent(Int64.self, forKey: "userId")
        latitude = try container.decodeIfPresent(Double.self, forKey: "latitude")
        longtitude = try container.decodeIfPresent(Double.self, forKey: "longtitude")
    }
}

