//
// DeviceLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class DeviceLocation: Codable {

    public var serialnumber: String?
    public var latitude: Double?
    public var longitude: Double?


    
    public init(serialnumber: String?, latitude: Double?, longitude: Double?) {
        self.serialnumber = serialnumber
        self.latitude = latitude
        self.longitude = longitude
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(serialnumber, forKey: "serialnumber")
        try container.encodeIfPresent(latitude, forKey: "latitude")
        try container.encodeIfPresent(longitude, forKey: "longitude")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        serialnumber = try container.decodeIfPresent(String.self, forKey: "serialnumber")
        latitude = try container.decodeIfPresent(Double.self, forKey: "latitude")
        longitude = try container.decodeIfPresent(Double.self, forKey: "longitude")
    }
}

