//
// HomeSearchResultSearchHomeDeviceModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class HomeSearchResultSearchHomeDeviceModel: Codable {

    public var totalNoOfRecords: Int64?
    public var records: [SearchHomeDeviceModel]?


    
    public init(totalNoOfRecords: Int64?, records: [SearchHomeDeviceModel]?) {
        self.totalNoOfRecords = totalNoOfRecords
        self.records = records
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(totalNoOfRecords, forKey: "totalNoOfRecords")
        try container.encodeIfPresent(records, forKey: "records")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        totalNoOfRecords = try container.decodeIfPresent(Int64.self, forKey: "totalNoOfRecords")
        records = try container.decodeIfPresent([SearchHomeDeviceModel].self, forKey: "records")
    }
}

