//
// InspectionViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/**  */

public class InspectionViewModel: Codable {

    /** Gets or sets the inspection identifier. */
    public var inspectionId: Int64


    
    public init(inspectionId: Int64) {
        self.inspectionId = inspectionId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(inspectionId, forKey: "inspectionId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        inspectionId = try container.decode(Int64.self, forKey: "inspectionId")
    }
}

