//
// InspectionImageModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class InspectionImageModel: Codable {

    public var inspectionId: Int64?
    public var imageData: String?
    public var userId: Int64?
    public var imageHash: String?


    
    public init(inspectionId: Int64?, imageData: String?, userId: Int64?, imageHash: String?) {
        self.inspectionId = inspectionId
        self.imageData = imageData
        self.userId = userId
        self.imageHash = imageHash
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(inspectionId, forKey: "inspectionId")
        try container.encodeIfPresent(imageData, forKey: "imageData")
        try container.encodeIfPresent(userId, forKey: "userId")
        try container.encodeIfPresent(imageHash, forKey: "imageHash")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        inspectionId = try container.decodeIfPresent(Int64.self, forKey: "inspectionId")
        imageData = try container.decodeIfPresent(String.self, forKey: "imageData")
        userId = try container.decodeIfPresent(Int64.self, forKey: "userId")
        imageHash = try container.decodeIfPresent(String.self, forKey: "imageHash")
    }
}

