//
// LatLon.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class LatLon: Codable {

    public var latitude: Double?
    public var longtitude: Double?


    
    public init(latitude: Double?, longtitude: Double?) {
        self.latitude = latitude
        self.longtitude = longtitude
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(latitude, forKey: "latitude")
        try container.encodeIfPresent(longtitude, forKey: "longtitude")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        latitude = try container.decodeIfPresent(Double.self, forKey: "latitude")
        longtitude = try container.decodeIfPresent(Double.self, forKey: "longtitude")
    }
}

