//
// MobileSettingsUpdateModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class MobileSettingsUpdateModel: Codable {

    public var settingName: String?
    public var settingValue: String?


    
    public init(settingName: String?, settingValue: String?) {
        self.settingName = settingName
        self.settingValue = settingValue
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(settingName, forKey: "settingName")
        try container.encodeIfPresent(settingValue, forKey: "settingValue")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        settingName = try container.decodeIfPresent(String.self, forKey: "settingName")
        settingValue = try container.decodeIfPresent(String.self, forKey: "settingValue")
    }
}

