//
// NotificationList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class NotificationList: Codable {

    public var key: String?
    public var items: [AppUserNotification]?


    
    public init(key: String?, items: [AppUserNotification]?) {
        self.key = key
        self.items = items
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(key, forKey: "key")
        try container.encodeIfPresent(items, forKey: "items")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        key = try container.decodeIfPresent(String.self, forKey: "key")
        items = try container.decodeIfPresent([AppUserNotification].self, forKey: "items")
    }
}

