//
// ReadingDeviceinformation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class ReadingDeviceinformation: Codable {

    public var serialNumber: String?
    public var batteryPercent: String?


    
    public init(serialNumber: String?, batteryPercent: String?) {
        self.serialNumber = serialNumber
        self.batteryPercent = batteryPercent
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(serialNumber, forKey: "serialNumber")
        try container.encodeIfPresent(batteryPercent, forKey: "batteryPercent")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        serialNumber = try container.decodeIfPresent(String.self, forKey: "serialNumber")
        batteryPercent = try container.decodeIfPresent(String.self, forKey: "batteryPercent")
    }
}

