//
// RenameDeviceViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class RenameDeviceViewModel: Codable {

    public var name: String?
    public var deviceId: Int64?


    
    public init(name: String?, deviceId: Int64?) {
        self.name = name
        self.deviceId = deviceId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(deviceId, forKey: "deviceId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        name = try container.decodeIfPresent(String.self, forKey: "name")
        deviceId = try container.decodeIfPresent(Int64.self, forKey: "deviceId")
    }
}

