//
// SalesForceDevices.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class SalesForceDevices: Codable {

    public var serialNumber: String?
    public var modelNumber: String?
    public var endDate: String?
    public var issaved: Bool?


    
    public init(serialNumber: String?, modelNumber: String?, endDate: String?, issaved: Bool?) {
        self.serialNumber = serialNumber
        self.modelNumber = modelNumber
        self.endDate = endDate
        self.issaved = issaved
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(serialNumber, forKey: "serialNumber")
        try container.encodeIfPresent(modelNumber, forKey: "modelNumber")
        try container.encodeIfPresent(endDate, forKey: "endDate")
        try container.encodeIfPresent(issaved, forKey: "issaved")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        serialNumber = try container.decodeIfPresent(String.self, forKey: "serialNumber")
        modelNumber = try container.decodeIfPresent(String.self, forKey: "modelNumber")
        endDate = try container.decodeIfPresent(String.self, forKey: "endDate")
        issaved = try container.decodeIfPresent(Bool.self, forKey: "issaved")
    }
}

