//
// SettingsUpdateModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class SettingsUpdateModel: Codable {

    public var radonUnitTypeId: Int64?
    public var stateNoticeId: Int64?
    public var comments: String?
    public var isSelectedSignatureImageForReport: Bool?
    public var isSelectedRadonRiskInformationForReport: Bool?
    public var isSelectedUnderstandingRadonTestResults: Bool?
    public var isSelectedEpaAverage: Bool?
    public var isSelectedOverallAverage: Bool?
    public var isSelectedLicenseNo: Bool?
    public var isSelectedTestData: Bool?
    public var isSelectedTestChart: Bool?
    public var companyAddress1: String?
    public var companyAddress2: String?
    public var companyCity: Int64?
    public var companyState: Int64?
    public var companyZip: String?
    public var companyPhonenumber: String?
    public var companyLicenseNumber: String?
    public var companyName: String?
    public var enableNotifications: Bool?
    public var sendNotificationonDataSync: Bool?
    public var sendNotificationOnSncApproval: Bool?
    public var alignmentId: Int64?
    public var actionLevel: Double?
    public var pressureUnitTypeId: Int64?
    public var temperatureUnitTypeId: Int64?
    public var isTextNotificationEnabled: Bool?
    public var isEmailNotificationEnabled: Bool?
    public var isMobileNotificationFrequencyEnabled: Bool?
    public var isSummaryEmailEnabled: Bool?
    public var isDailySummaryEmailEnabled: Bool?
    public var isWeeklySummaryEmailEnabled: Bool?
    public var isMonthlySummaryEmailEnabled: Bool?
    public var notificationEmail: String?
    public var mobileNo: String?
    public var id: Int64?
    public var radonThresholdWarningLevel: Double?
    public var radonThresholdAlertLevel: Double?
    public var temperatureThresholdHighWarningLevel: Double?
    public var temperatureThresholdLowalertLevel: Double?
    public var temperatureThresholdLowWarningLevel: Double?
    public var temperatureThresholdHighalertLevel: Double?
    public var humidityThresholdLowWarningLevel: Double?
    public var humidityThresholdHighWarningLevel: Double?
    public var humidityThresholdLowalertLevel: Double?
    public var humidityThresholdHighalertLevel: Double?
    public var airpressureThresholdLowWarningLevel: Double?
    public var airpressureThresholdHighWarningLevel: Double?
    public var airpressureThresholdLowalertLevel: Double?
    public var airpressureThresholdHighalertLevel: Double?
    public var co2ThresholdWarningLevel: Double?
    public var co2ThresholdAlertLevel: Double?
    public var vocThresholdWarningLevel: Double?
    public var vocThresholdAlertLevel: Double?
    public var temperatureRadonUnits: Int?
    public var humidityRadonUnits: Int?
    public var airpressureRadonUnits: Int?
    public var timeZone: Int?


    
    public init(radonUnitTypeId: Int64?, stateNoticeId: Int64?, comments: String?, isSelectedSignatureImageForReport: Bool?, isSelectedRadonRiskInformationForReport: Bool?, isSelectedUnderstandingRadonTestResults: Bool?, isSelectedEpaAverage: Bool?, isSelectedOverallAverage: Bool?, isSelectedLicenseNo: Bool?, isSelectedTestData: Bool?, isSelectedTestChart: Bool?, companyAddress1: String?, companyAddress2: String?, companyCity: Int64?, companyState: Int64?, companyZip: String?, companyPhonenumber: String?, companyLicenseNumber: String?, companyName: String?, enableNotifications: Bool?, sendNotificationonDataSync: Bool?, sendNotificationOnSncApproval: Bool?, alignmentId: Int64?, actionLevel: Double?, pressureUnitTypeId: Int64?, temperatureUnitTypeId: Int64?, isTextNotificationEnabled: Bool?, isEmailNotificationEnabled: Bool?, isMobileNotificationFrequencyEnabled: Bool?, isSummaryEmailEnabled: Bool?, isDailySummaryEmailEnabled: Bool?, isWeeklySummaryEmailEnabled: Bool?, isMonthlySummaryEmailEnabled: Bool?, notificationEmail: String?, mobileNo: String?, id: Int64?, radonThresholdWarningLevel: Double?, radonThresholdAlertLevel: Double?, temperatureThresholdHighWarningLevel: Double?, temperatureThresholdLowalertLevel: Double?, temperatureThresholdLowWarningLevel: Double?, temperatureThresholdHighalertLevel: Double?, humidityThresholdLowWarningLevel: Double?, humidityThresholdHighWarningLevel: Double?, humidityThresholdLowalertLevel: Double?, humidityThresholdHighalertLevel: Double?, airpressureThresholdLowWarningLevel: Double?, airpressureThresholdHighWarningLevel: Double?, airpressureThresholdLowalertLevel: Double?, airpressureThresholdHighalertLevel: Double?, co2ThresholdWarningLevel: Double?, co2ThresholdAlertLevel: Double?, vocThresholdWarningLevel: Double?, vocThresholdAlertLevel: Double?, temperatureRadonUnits: Int?, humidityRadonUnits: Int?, airpressureRadonUnits: Int?, timeZone: Int?) {
        self.radonUnitTypeId = radonUnitTypeId
        self.stateNoticeId = stateNoticeId
        self.comments = comments
        self.isSelectedSignatureImageForReport = isSelectedSignatureImageForReport
        self.isSelectedRadonRiskInformationForReport = isSelectedRadonRiskInformationForReport
        self.isSelectedUnderstandingRadonTestResults = isSelectedUnderstandingRadonTestResults
        self.isSelectedEpaAverage = isSelectedEpaAverage
        self.isSelectedOverallAverage = isSelectedOverallAverage
        self.isSelectedLicenseNo = isSelectedLicenseNo
        self.isSelectedTestData = isSelectedTestData
        self.isSelectedTestChart = isSelectedTestChart
        self.companyAddress1 = companyAddress1
        self.companyAddress2 = companyAddress2
        self.companyCity = companyCity
        self.companyState = companyState
        self.companyZip = companyZip
        self.companyPhonenumber = companyPhonenumber
        self.companyLicenseNumber = companyLicenseNumber
        self.companyName = companyName
        self.enableNotifications = enableNotifications
        self.sendNotificationonDataSync = sendNotificationonDataSync
        self.sendNotificationOnSncApproval = sendNotificationOnSncApproval
        self.alignmentId = alignmentId
        self.actionLevel = actionLevel
        self.pressureUnitTypeId = pressureUnitTypeId
        self.temperatureUnitTypeId = temperatureUnitTypeId
        self.isTextNotificationEnabled = isTextNotificationEnabled
        self.isEmailNotificationEnabled = isEmailNotificationEnabled
        self.isMobileNotificationFrequencyEnabled = isMobileNotificationFrequencyEnabled
        self.isSummaryEmailEnabled = isSummaryEmailEnabled
        self.isDailySummaryEmailEnabled = isDailySummaryEmailEnabled
        self.isWeeklySummaryEmailEnabled = isWeeklySummaryEmailEnabled
        self.isMonthlySummaryEmailEnabled = isMonthlySummaryEmailEnabled
        self.notificationEmail = notificationEmail
        self.mobileNo = mobileNo
        self.id = id
        self.radonThresholdWarningLevel = radonThresholdWarningLevel
        self.radonThresholdAlertLevel = radonThresholdAlertLevel
        self.temperatureThresholdHighWarningLevel = temperatureThresholdHighWarningLevel
        self.temperatureThresholdLowalertLevel = temperatureThresholdLowalertLevel
        self.temperatureThresholdLowWarningLevel = temperatureThresholdLowWarningLevel
        self.temperatureThresholdHighalertLevel = temperatureThresholdHighalertLevel
        self.humidityThresholdLowWarningLevel = humidityThresholdLowWarningLevel
        self.humidityThresholdHighWarningLevel = humidityThresholdHighWarningLevel
        self.humidityThresholdLowalertLevel = humidityThresholdLowalertLevel
        self.humidityThresholdHighalertLevel = humidityThresholdHighalertLevel
        self.airpressureThresholdLowWarningLevel = airpressureThresholdLowWarningLevel
        self.airpressureThresholdHighWarningLevel = airpressureThresholdHighWarningLevel
        self.airpressureThresholdLowalertLevel = airpressureThresholdLowalertLevel
        self.airpressureThresholdHighalertLevel = airpressureThresholdHighalertLevel
        self.co2ThresholdWarningLevel = co2ThresholdWarningLevel
        self.co2ThresholdAlertLevel = co2ThresholdAlertLevel
        self.vocThresholdWarningLevel = vocThresholdWarningLevel
        self.vocThresholdAlertLevel = vocThresholdAlertLevel
        self.temperatureRadonUnits = temperatureRadonUnits
        self.humidityRadonUnits = humidityRadonUnits
        self.airpressureRadonUnits = airpressureRadonUnits
        self.timeZone = timeZone
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(radonUnitTypeId, forKey: "radonUnitTypeId")
        try container.encodeIfPresent(stateNoticeId, forKey: "stateNoticeId")
        try container.encodeIfPresent(comments, forKey: "comments")
        try container.encodeIfPresent(isSelectedSignatureImageForReport, forKey: "isSelectedSignatureImageForReport")
        try container.encodeIfPresent(isSelectedRadonRiskInformationForReport, forKey: "isSelectedRadonRiskInformationForReport")
        try container.encodeIfPresent(isSelectedUnderstandingRadonTestResults, forKey: "isSelectedUnderstandingRadonTestResults")
        try container.encodeIfPresent(isSelectedEpaAverage, forKey: "isSelectedEpaAverage")
        try container.encodeIfPresent(isSelectedOverallAverage, forKey: "isSelectedOverallAverage")
        try container.encodeIfPresent(isSelectedLicenseNo, forKey: "isSelectedLicenseNo")
        try container.encodeIfPresent(isSelectedTestData, forKey: "isSelectedTestData")
        try container.encodeIfPresent(isSelectedTestChart, forKey: "isSelectedTestChart")
        try container.encodeIfPresent(companyAddress1, forKey: "companyAddress1")
        try container.encodeIfPresent(companyAddress2, forKey: "companyAddress2")
        try container.encodeIfPresent(companyCity, forKey: "companyCity")
        try container.encodeIfPresent(companyState, forKey: "companyState")
        try container.encodeIfPresent(companyZip, forKey: "companyZip")
        try container.encodeIfPresent(companyPhonenumber, forKey: "companyPhonenumber")
        try container.encodeIfPresent(companyLicenseNumber, forKey: "companyLicenseNumber")
        try container.encodeIfPresent(companyName, forKey: "companyName")
        try container.encodeIfPresent(enableNotifications, forKey: "enableNotifications")
        try container.encodeIfPresent(sendNotificationonDataSync, forKey: "sendNotificationonDataSync")
        try container.encodeIfPresent(sendNotificationOnSncApproval, forKey: "sendNotificationOnSncApproval")
        try container.encodeIfPresent(alignmentId, forKey: "alignmentId")
        try container.encodeIfPresent(actionLevel, forKey: "actionLevel")
        try container.encodeIfPresent(pressureUnitTypeId, forKey: "pressureUnitTypeId")
        try container.encodeIfPresent(temperatureUnitTypeId, forKey: "temperatureUnitTypeId")
        try container.encodeIfPresent(isTextNotificationEnabled, forKey: "isTextNotificationEnabled")
        try container.encodeIfPresent(isEmailNotificationEnabled, forKey: "isEmailNotificationEnabled")
        try container.encodeIfPresent(isMobileNotificationFrequencyEnabled, forKey: "isMobileNotificationFrequencyEnabled")
        try container.encodeIfPresent(isSummaryEmailEnabled, forKey: "isSummaryEmailEnabled")
        try container.encodeIfPresent(isDailySummaryEmailEnabled, forKey: "isDailySummaryEmailEnabled")
        try container.encodeIfPresent(isWeeklySummaryEmailEnabled, forKey: "isWeeklySummaryEmailEnabled")
        try container.encodeIfPresent(isMonthlySummaryEmailEnabled, forKey: "isMonthlySummaryEmailEnabled")
        try container.encodeIfPresent(notificationEmail, forKey: "notificationEmail")
        try container.encodeIfPresent(mobileNo, forKey: "mobileNo")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(radonThresholdWarningLevel, forKey: "radonThresholdWarningLevel")
        try container.encodeIfPresent(radonThresholdAlertLevel, forKey: "radonThresholdAlertLevel")
        try container.encodeIfPresent(temperatureThresholdHighWarningLevel, forKey: "temperatureThresholdHighWarningLevel")
        try container.encodeIfPresent(temperatureThresholdLowalertLevel, forKey: "temperatureThresholdLowalertLevel")
        try container.encodeIfPresent(temperatureThresholdLowWarningLevel, forKey: "temperatureThresholdLowWarningLevel")
        try container.encodeIfPresent(temperatureThresholdHighalertLevel, forKey: "temperatureThresholdHighalertLevel")
        try container.encodeIfPresent(humidityThresholdLowWarningLevel, forKey: "humidityThresholdLowWarningLevel")
        try container.encodeIfPresent(humidityThresholdHighWarningLevel, forKey: "humidityThresholdHighWarningLevel")
        try container.encodeIfPresent(humidityThresholdLowalertLevel, forKey: "humidityThresholdLowalertLevel")
        try container.encodeIfPresent(humidityThresholdHighalertLevel, forKey: "humidityThresholdHighalertLevel")
        try container.encodeIfPresent(airpressureThresholdLowWarningLevel, forKey: "airpressureThresholdLowWarningLevel")
        try container.encodeIfPresent(airpressureThresholdHighWarningLevel, forKey: "airpressureThresholdHighWarningLevel")
        try container.encodeIfPresent(airpressureThresholdLowalertLevel, forKey: "airpressureThresholdLowalertLevel")
        try container.encodeIfPresent(airpressureThresholdHighalertLevel, forKey: "airpressureThresholdHighalertLevel")
        try container.encodeIfPresent(co2ThresholdWarningLevel, forKey: "co2ThresholdWarningLevel")
        try container.encodeIfPresent(co2ThresholdAlertLevel, forKey: "co2ThresholdAlertLevel")
        try container.encodeIfPresent(vocThresholdWarningLevel, forKey: "vocThresholdWarningLevel")
        try container.encodeIfPresent(vocThresholdAlertLevel, forKey: "vocThresholdAlertLevel")
        try container.encodeIfPresent(temperatureRadonUnits, forKey: "temperatureRadonUnits")
        try container.encodeIfPresent(humidityRadonUnits, forKey: "humidityRadonUnits")
        try container.encodeIfPresent(airpressureRadonUnits, forKey: "airpressureRadonUnits")
        try container.encodeIfPresent(timeZone, forKey: "timeZone")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        radonUnitTypeId = try container.decodeIfPresent(Int64.self, forKey: "radonUnitTypeId")
        stateNoticeId = try container.decodeIfPresent(Int64.self, forKey: "stateNoticeId")
        comments = try container.decodeIfPresent(String.self, forKey: "comments")
        isSelectedSignatureImageForReport = try container.decodeIfPresent(Bool.self, forKey: "isSelectedSignatureImageForReport")
        isSelectedRadonRiskInformationForReport = try container.decodeIfPresent(Bool.self, forKey: "isSelectedRadonRiskInformationForReport")
        isSelectedUnderstandingRadonTestResults = try container.decodeIfPresent(Bool.self, forKey: "isSelectedUnderstandingRadonTestResults")
        isSelectedEpaAverage = try container.decodeIfPresent(Bool.self, forKey: "isSelectedEpaAverage")
        isSelectedOverallAverage = try container.decodeIfPresent(Bool.self, forKey: "isSelectedOverallAverage")
        isSelectedLicenseNo = try container.decodeIfPresent(Bool.self, forKey: "isSelectedLicenseNo")
        isSelectedTestData = try container.decodeIfPresent(Bool.self, forKey: "isSelectedTestData")
        isSelectedTestChart = try container.decodeIfPresent(Bool.self, forKey: "isSelectedTestChart")
        companyAddress1 = try container.decodeIfPresent(String.self, forKey: "companyAddress1")
        companyAddress2 = try container.decodeIfPresent(String.self, forKey: "companyAddress2")
        companyCity = try container.decodeIfPresent(Int64.self, forKey: "companyCity")
        companyState = try container.decodeIfPresent(Int64.self, forKey: "companyState")
        companyZip = try container.decodeIfPresent(String.self, forKey: "companyZip")
        companyPhonenumber = try container.decodeIfPresent(String.self, forKey: "companyPhonenumber")
        companyLicenseNumber = try container.decodeIfPresent(String.self, forKey: "companyLicenseNumber")
        companyName = try container.decodeIfPresent(String.self, forKey: "companyName")
        enableNotifications = try container.decodeIfPresent(Bool.self, forKey: "enableNotifications")
        sendNotificationonDataSync = try container.decodeIfPresent(Bool.self, forKey: "sendNotificationonDataSync")
        sendNotificationOnSncApproval = try container.decodeIfPresent(Bool.self, forKey: "sendNotificationOnSncApproval")
        alignmentId = try container.decodeIfPresent(Int64.self, forKey: "alignmentId")
        actionLevel = try container.decodeIfPresent(Double.self, forKey: "actionLevel")
        pressureUnitTypeId = try container.decodeIfPresent(Int64.self, forKey: "pressureUnitTypeId")
        temperatureUnitTypeId = try container.decodeIfPresent(Int64.self, forKey: "temperatureUnitTypeId")
        isTextNotificationEnabled = try container.decodeIfPresent(Bool.self, forKey: "isTextNotificationEnabled")
        isEmailNotificationEnabled = try container.decodeIfPresent(Bool.self, forKey: "isEmailNotificationEnabled")
        isMobileNotificationFrequencyEnabled = try container.decodeIfPresent(Bool.self, forKey: "isMobileNotificationFrequencyEnabled")
        isSummaryEmailEnabled = try container.decodeIfPresent(Bool.self, forKey: "isSummaryEmailEnabled")
        isDailySummaryEmailEnabled = try container.decodeIfPresent(Bool.self, forKey: "isDailySummaryEmailEnabled")
        isWeeklySummaryEmailEnabled = try container.decodeIfPresent(Bool.self, forKey: "isWeeklySummaryEmailEnabled")
        isMonthlySummaryEmailEnabled = try container.decodeIfPresent(Bool.self, forKey: "isMonthlySummaryEmailEnabled")
        notificationEmail = try container.decodeIfPresent(String.self, forKey: "notificationEmail")
        mobileNo = try container.decodeIfPresent(String.self, forKey: "mobileNo")
        id = try container.decodeIfPresent(Int64.self, forKey: "id")
        radonThresholdWarningLevel = try container.decodeIfPresent(Double.self, forKey: "radonThresholdWarningLevel")
        radonThresholdAlertLevel = try container.decodeIfPresent(Double.self, forKey: "radonThresholdAlertLevel")
        temperatureThresholdHighWarningLevel = try container.decodeIfPresent(Double.self, forKey: "temperatureThresholdHighWarningLevel")
        temperatureThresholdLowalertLevel = try container.decodeIfPresent(Double.self, forKey: "temperatureThresholdLowalertLevel")
        temperatureThresholdLowWarningLevel = try container.decodeIfPresent(Double.self, forKey: "temperatureThresholdLowWarningLevel")
        temperatureThresholdHighalertLevel = try container.decodeIfPresent(Double.self, forKey: "temperatureThresholdHighalertLevel")
        humidityThresholdLowWarningLevel = try container.decodeIfPresent(Double.self, forKey: "humidityThresholdLowWarningLevel")
        humidityThresholdHighWarningLevel = try container.decodeIfPresent(Double.self, forKey: "humidityThresholdHighWarningLevel")
        humidityThresholdLowalertLevel = try container.decodeIfPresent(Double.self, forKey: "humidityThresholdLowalertLevel")
        humidityThresholdHighalertLevel = try container.decodeIfPresent(Double.self, forKey: "humidityThresholdHighalertLevel")
        airpressureThresholdLowWarningLevel = try container.decodeIfPresent(Double.self, forKey: "airpressureThresholdLowWarningLevel")
        airpressureThresholdHighWarningLevel = try container.decodeIfPresent(Double.self, forKey: "airpressureThresholdHighWarningLevel")
        airpressureThresholdLowalertLevel = try container.decodeIfPresent(Double.self, forKey: "airpressureThresholdLowalertLevel")
        airpressureThresholdHighalertLevel = try container.decodeIfPresent(Double.self, forKey: "airpressureThresholdHighalertLevel")
        co2ThresholdWarningLevel = try container.decodeIfPresent(Double.self, forKey: "co2ThresholdWarningLevel")
        co2ThresholdAlertLevel = try container.decodeIfPresent(Double.self, forKey: "co2ThresholdAlertLevel")
        vocThresholdWarningLevel = try container.decodeIfPresent(Double.self, forKey: "vocThresholdWarningLevel")
        vocThresholdAlertLevel = try container.decodeIfPresent(Double.self, forKey: "vocThresholdAlertLevel")
        temperatureRadonUnits = try container.decodeIfPresent(Int.self, forKey: "temperatureRadonUnits")
        humidityRadonUnits = try container.decodeIfPresent(Int.self, forKey: "humidityRadonUnits")
        airpressureRadonUnits = try container.decodeIfPresent(Int.self, forKey: "airpressureRadonUnits")
        timeZone = try container.decodeIfPresent(Int.self, forKey: "timeZone")
    }
}

