//
// SimpleCluster.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class SimpleCluster: Codable {

    public var id: Int?
    public var data: [String]?
    public var latLonCenter: LATLONG?
    public var latLonList: [LATLONG]?


    
    public init(id: Int?, data: [String]?, latLonCenter: LATLONG?, latLonList: [LATLONG]?) {
        self.id = id
        self.data = data
        self.latLonCenter = latLonCenter
        self.latLonList = latLonList
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(data, forKey: "data")
        try container.encodeIfPresent(latLonCenter, forKey: "latLonCenter")
        try container.encodeIfPresent(latLonList, forKey: "latLonList")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(Int.self, forKey: "id")
        data = try container.decodeIfPresent([String].self, forKey: "data")
        latLonCenter = try container.decodeIfPresent(LATLONG.self, forKey: "latLonCenter")
        latLonList = try container.decodeIfPresent([LATLONG].self, forKey: "latLonList")
    }
}

