//
// SNAirQualityWebViewModelsUpdateBluetoothSync.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SNAirQualityWebViewModelsUpdateBluetoothSync: Codable {

    public var timeStampUtc: Int64?
    public var deviceId: Int64?

    public init(timeStampUtc: Int64?, deviceId: Int64?) {
        self.timeStampUtc = timeStampUtc
        self.deviceId = deviceId
    }


}

