//
// TemperatureModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class TemperatureModel: Codable {

    public var unit: String?
    public var min: String?
    public var max: String?
    public var average: String?


    
    public init(unit: String?, min: String?, max: String?, average: String?) {
        self.unit = unit
        self.min = min
        self.max = max
        self.average = average
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(unit, forKey: "unit")
        try container.encodeIfPresent(min, forKey: "min")
        try container.encodeIfPresent(max, forKey: "max")
        try container.encodeIfPresent(average, forKey: "average")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        unit = try container.decodeIfPresent(String.self, forKey: "unit")
        min = try container.decodeIfPresent(String.self, forKey: "min")
        max = try container.decodeIfPresent(String.self, forKey: "max")
        average = try container.decodeIfPresent(String.self, forKey: "average")
    }
}

