//
// TestDetailsModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class TestDetailsModel: Codable {

    public var radonConcentration: RadonConcentrationModel?
    public var temperature: TemperatureModel?
    public var humidity: HumidityModel?
    public var pressure: PressureModel?


    
    public init(radonConcentration: RadonConcentrationModel?, temperature: TemperatureModel?, humidity: HumidityModel?, pressure: PressureModel?) {
        self.radonConcentration = radonConcentration
        self.temperature = temperature
        self.humidity = humidity
        self.pressure = pressure
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(radonConcentration, forKey: "radonConcentration")
        try container.encodeIfPresent(temperature, forKey: "temperature")
        try container.encodeIfPresent(humidity, forKey: "humidity")
        try container.encodeIfPresent(pressure, forKey: "pressure")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        radonConcentration = try container.decodeIfPresent(RadonConcentrationModel.self, forKey: "radonConcentration")
        temperature = try container.decodeIfPresent(TemperatureModel.self, forKey: "temperature")
        humidity = try container.decodeIfPresent(HumidityModel.self, forKey: "humidity")
        pressure = try container.decodeIfPresent(PressureModel.self, forKey: "pressure")
    }
}

