//
// TransferInspectionViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Refresents Transfer inspection model */

public class TransferInspectionViewModel: Codable {

    /** Gets or sets the license no. */
    public var licenseNo: String
    /** Gets or sets the comments. */
    public var comments: String?
    /** Gets or sets the inspection identifier. */
    public var inspectionId: Int64


    
    public init(licenseNo: String, comments: String?, inspectionId: Int64) {
        self.licenseNo = licenseNo
        self.comments = comments
        self.inspectionId = inspectionId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(licenseNo, forKey: "licenseNo")
        try container.encodeIfPresent(comments, forKey: "comments")
        try container.encode(inspectionId, forKey: "inspectionId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        licenseNo = try container.decode(String.self, forKey: "licenseNo")
        comments = try container.decodeIfPresent(String.self, forKey: "comments")
        inspectionId = try container.decode(Int64.self, forKey: "inspectionId")
    }
}

