//
// UpdateDeviceSettingViewModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class UpdateDeviceSettingViewModel: Codable {

    public var name: String?
    public var value: String?
    public var deviceId: Int64?


    
    public init(name: String?, value: String?, deviceId: Int64?) {
        self.name = name
        self.value = value
        self.deviceId = deviceId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(value, forKey: "value")
        try container.encodeIfPresent(deviceId, forKey: "deviceId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        name = try container.decodeIfPresent(String.self, forKey: "name")
        value = try container.decodeIfPresent(String.self, forKey: "value")
        deviceId = try container.decodeIfPresent(Int64.self, forKey: "deviceId")
    }
}

