//
// UserProfileDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public class UserProfileDetails: Codable {

    public var userid: Int64?
    public var firstname: String?
    public var lastname: String?
    public var profileimage: String?


    
    public init(userid: Int64?, firstname: String?, lastname: String?, profileimage: String?) {
        self.userid = userid
        self.firstname = firstname
        self.lastname = lastname
        self.profileimage = profileimage
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(userid, forKey: "userid")
        try container.encodeIfPresent(firstname, forKey: "firstname")
        try container.encodeIfPresent(lastname, forKey: "lastname")
        try container.encodeIfPresent(profileimage, forKey: "profileimage")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        userid = try container.decodeIfPresent(Int64.self, forKey: "userid")
        firstname = try container.decodeIfPresent(String.self, forKey: "firstname")
        lastname = try container.decodeIfPresent(String.self, forKey: "lastname")
        profileimage = try container.decodeIfPresent(String.self, forKey: "profileimage")
    }
}

